// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKcCTS4d0Jpx5aXuEeYqyk4S_NSMUUKSo',
    appId: '1:520791556814:web:896581c7c904338595869f',
    messagingSenderId: '520791556814',
    projectId: 'runner-sos-project',
    authDomain: 'runner-sos-project.firebaseapp.com',
    storageBucket: 'runner-sos-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYaIv4QVZLVRRSEV4IIlxL06arhiocCCg',
    appId: '1:520791556814:android:b67210bcf831e53995869f',
    messagingSenderId: '520791556814',
    projectId: 'runner-sos-project',
    storageBucket: 'runner-sos-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Kq5K61v1B_x8BcPjfXRDlr0Vgew_HNg',
    appId: '1:520791556814:ios:b64c7562e962cb4b95869f',
    messagingSenderId: '520791556814',
    projectId: 'runner-sos-project',
    storageBucket: 'runner-sos-project.firebasestorage.app',
    iosBundleId: 'com.example.runnerSos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Kq5K61v1B_x8BcPjfXRDlr0Vgew_HNg',
    appId: '1:520791556814:ios:b64c7562e962cb4b95869f',
    messagingSenderId: '520791556814',
    projectId: 'runner-sos-project',
    storageBucket: 'runner-sos-project.firebasestorage.app',
    iosBundleId: 'com.example.runnerSos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKcCTS4d0Jpx5aXuEeYqyk4S_NSMUUKSo',
    appId: '1:520791556814:web:ac8bd3d86c2d079f95869f',
    messagingSenderId: '520791556814',
    projectId: 'runner-sos-project',
    authDomain: 'runner-sos-project.firebaseapp.com',
    storageBucket: 'runner-sos-project.firebasestorage.app',
  );
}
